name: "she's been busy"
favicon: null
layout_spectrum: 0.50073
typography_spectrum: 0.1202
title: what have i been up to?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1a191e'
    - '#73787b'
    - '#524d4a'
    - '#adb6bf'
    - '#619aad'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
