name: "she's been busy"
favicon: null
layout_spectrum: 1
typography_spectrum: 0.11641
title: what have i been up to?
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3125
  lightness: 0.3125
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
